#!/bin/sh
GREEN="\033[92m"
NORMAL="\033[0m"

which scons > /dev/null
if [ $? -eq 0 ]
then
	if [ ! -d 'scons-local-0.96.1' ]
	then
		tar xjvf scons-mini.tar.bz2
		echo ""
		echo -e $GREEN"A minimum scons distribution has been unpacked right here"
		echo -e $GREEN"you can now run : "$NORMAL
		echo -e $BOLD"./scons"$NORMAL
		echo -e $BOLD"./scons install$NORMAL (as root probably)"
	fi
fi
