msgmerge -U de.po knetstats.pot
msgmerge -U es.po knetstats.pot
msgmerge -U fr.po knetstats.pot
msgmerge -U it.po knetstats.pot
msgmerge -U ky_KG.po knetstats.pot
msgmerge -U pl.po knetstats.pot
msgmerge -U pt_BR.po knetstats.pot
msgmerge -U ru_RU.po knetstats.pot
msgmerge -U bg.po knetstats.pot
